### ISSUE TITLE
Move content out one folder

### ISSUE THREAD

**Issue by Brottweiler** [donzooles/omega-for-mumble#20]
When cloning this repo, the repo is a folder. Because of this, the actual folder with the theme is inside another folder, so you cannot select the theme.

This is how it is when you clone it: `.local/share/Mumble/Mumble/Themes/omega-for-mumble/omega-for-mumble`, but it *should* be `.local/share/Mumble/Mumble/Themes/omega-for-mumble` for it to work. 

If you look at [MetroMumble](https://github.com/xPoke/MetroMumble), this is how that folder structure is.

**Comment by donzooles** [comment]
If you download releases then you get the normal folder structure. It's just to get a cleaner repo. :)

**Comment by Brottweiler** [comment]
Ah yeah, I prefer to just clone it though so I can pull any changes easily. I don't understand the logic with having "cleaner repo" when having a folder, although I suppose since you have readme, license and then the theme in a folder so the readme is not inside the theme folder.

I don't agree with this, but you decide. 😛

**Comment by donzooles** [comment]
Ok, I think I got your point. I moved the theme.ini one folder backwards to hopefully solve your problem. :)

**Comment by Brottweiler** [comment]
That did work, well, thank you for doing that change!
